[cheap_esp32c3-ht-ra62]
extends = esp32_base
board = seeed_xiao_esp32c3
build_flags =
  ${esp32_base.build_flags}
  -I variants/cheap_esp32c3-ht-ra62
  -D ESP32_CPU_FREQ=80
  -D PIN_VBAT_READ=0
  -D P_LORA_SCLK=10
  -D P_LORA_MISO=6
  -D P_LORA_MOSI=7
  -D P_LORA_DIO_1=20
  -D P_LORA_NSS=5
  -D P_LORA_RESET=21
  -D P_LORA_BUSY=4
  -D P_LORA_DIO_0=RADIOLIB_NC
  -D P_LORA_DIO_2=RADIOLIB_NC
  -D PIN_BOARD_SDA=1
  -D PIN_BOARD_SCL=0
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D SX126X_RX_BOOSTED_GAIN=1
  -D LORA_TX_POWER=22
;  -D SX126X_RXEN=D5
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/cheap_esp32c3-ht-ra62>
  +<helpers/sensors>
lib_deps =
  ${esp32_base.lib_deps}

[env:cheap_esp32c3-ht-ra62_repeater]
extends = cheap_esp32c3-ht-ra62
build_src_filter = ${cheap_esp32c3-ht-ra62.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
build_flags =
  ${cheap_esp32c3-ht-ra62.build_flags}
  ${sensor_base.build_flags}
  -UENV_INCLUDE_GPS
  -UENV_INCLUDE_VL53L0X
  -D ADVERT_NAME='"Custom ESP32C3-SX1262 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps =
  ${cheap_esp32c3-ht-ra62.lib_deps}
  ${sensor_base.lib_deps}
  ${esp32_ota.lib_deps}
  bakercp/CRC32 @ ^2.0.0

[env:cheap_esp32c3-ht-ra62_room_server]
extends = cheap_esp32c3-ht-ra62
build_src_filter = ${cheap_esp32c3-ht-ra62.build_src_filter}
  +<../examples/simple_room_server/*.cpp>
build_flags =
  ${cheap_esp32c3-ht-ra62.build_flags}
  ${sensor_base.build_flags}
  -UENV_INCLUDE_GPS
  -UENV_INCLUDE_VL53L0X
  -D ADVERT_NAME='"Custom ESP32C3-SX1262 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps =
  ${cheap_esp32c3-ht-ra62.lib_deps}
  ${sensor_base.lib_deps}
  ${esp32_ota.lib_deps}
  bakercp/CRC32 @ ^2.0.0

[env:cheap_esp32c3-ht-ra62_companion_radio_ble]
extends = cheap_esp32c3-ht-ra62
build_src_filter = ${cheap_esp32c3-ht-ra62.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-orig/*.cpp>
  +<helpers/esp32/*.cpp>
  +<helpers/ui/NullDisplayDriver.cpp>
build_flags =
  ${cheap_esp32c3-ht-ra62.build_flags}
  -I examples/companion_radio/ui-orig
  -D DISPLAY_CLASS=NullDisplayDriver
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=654321
  -D OFFLINE_QUEUE_SIZE=256
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
lib_deps =
  ${cheap_esp32c3-ht-ra62.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:cheap_esp32c3-ht-ra62_companion_radio_usb]
extends = cheap_esp32c3-ht-ra62
build_src_filter = ${cheap_esp32c3-ht-ra62.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-orig/*.cpp>
  +<helpers/esp32/*.cpp>
  +<helpers/ui/NullDisplayDriver.cpp>
build_flags =
  ${cheap_esp32c3-ht-ra62.build_flags}
  -I examples/companion_radio/ui-orig
  -D DISPLAY_CLASS=NullDisplayDriver
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
lib_deps =
  ${cheap_esp32c3-ht-ra62.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:cheap_esp32c3-ht-ra62_companion_radio_wifi]
extends = cheap_esp32c3-ht-ra62
build_src_filter = ${cheap_esp32c3-ht-ra62.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-orig/*.cpp>
  +<helpers/esp32/*.cpp>
  +<helpers/ui/NullDisplayDriver.cpp>
build_flags =
  ${cheap_esp32c3-ht-ra62.build_flags}
  -I examples/companion_radio/ui-orig
  -D DISPLAY_CLASS=NullDisplayDriver
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
  -D WIFI_DEBUG_LOGGING=1
  -D WIFI_SSID='"myssid"'
  -D WIFI_PWD='"mypwd"'
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
lib_deps =
  ${cheap_esp32c3-ht-ra62.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0
